ln -s ../G2S*raw .
ln -s ../../PostProc_scripts/load_GeoAc_atmo.m .
ln -s ../../PostProc_scripts/plot_GeoAc_profile.m .
ln -s ../../PostProc_scripts/load_StationInfo.m .
ln -s ../../PostProc_scripts/load_GeoAc_raypaths.m .
ln -s ../../PostProc_scripts/plot_art2d.m .

echo "For 3d raytracing with GeoAc, you can generate the grid of profiles you need by running:"
echo "  ../g2s_Extract_Grid example1_step3_ext3d.ctr"
echo "or if you want to use Art2d or pape for propagation modeling along a transect, you can run:"
echo "  ../g2s_Extract_Xsec example1_step3_ext2d.ctr"

echo " "
echo "-------------------------------------------------"
echo "   GeoAc "
echo "      https://github.com/LANL-Seismoacoustics/GeoAc"
echo "-------------------------------------------------"
echo "For the forward 3-d Range-dependent GeoAc model, use (for a single azimuth):"
echo " GeoAcGlobal.RngDep -prop Bering Bering.loclat Bering.loclon theta_min=-30.0 theta_max=55.0 theta_step=1.0 \\"
echo "   azimuth=41.0 bounces=10 lat_src=52.8222 lon_src=-169.945 z_src=1.73 CalcAmp=False WriteAtmo=True"
echo " "
echo "For the forward 3-d Range-dependent GeoAc model, use (for a swath of azimuths):"
echo " GeoAcGlobal.RngDep -prop Bering Bering.loclat Bering.loclon theta_min=-30.0 theta_max=55.0 theta_step=1.0 \\"
echo "phi_min=40.0 phi_max=90.0 phi_step=5.0 bounces=10 lat_src=52.8222 lon_src=-169.945 z_src=1.73 CalcAmp=False WriteAtmo=True"
echo " "
echo "To plot, use plot_GeoAc_profile.m with either MatLab or octave "
echo " "
echo "-------------------------------------------------"
echo "   Artd2 "
echo "-------------------------------------------------"
echo "Art2d is no longer publically available, but if you have a copy, you can run it using the env file"
echo "created by g2s_Extract_Xsec above using the following script"
echo " ./run_art2d.sh"
echo " "
echo "To plot, use plot_art2d.m with either MatLab or octave "
echo " "
echo "-------------------------------------------------"
echo "   NCPA codes for a range dependent atmosphere "
echo "      https://github.com/chetzer-ncpa/ncpaprop"
echo "-------------------------------------------------"
echo "For the range dependent Modess (Model Effective Sound Speed), use"
echo " ModessRD1WCM --g2senvfile InfraAtmos01.env --atmosfileorder zuvwtdp --skiplines 0 \\"
echo "   --azimuth 41 --freq 0.1 --write_2D_TLoss --sourceheight_km 1.73"
echo " "
echo "For the range dependent pape (Wide-Angle Pade Parabolic Equation Code), use"
echo " pape --g2senvfile InfraAtmos01.env --atmosfileorder zuvwtdp --skiplines 0 --azimuth 41 --freq 0.1 \\"
echo "   --sourceheight_km 1.73 --receiverheight_km 0 --maxheight_km 180 --starter_type gaussian --n_pade 6 \\"
echo "   --maxrange_km 1000 --write_2D_TLoss --do_lossless"
echo " "
echo "To plot, use plot_tloss2d.m with either MatLab or octave "
echo " "
