#!/bin/bash

if [ $# -eq 0 ]
  then
  echo "No arguments supplied"
  echo "Usage: get_NGDC YYYY"
  echo "       where YYYY = year"
  exit
fi

APHOME=/opt/USGS/AVOG2S/ExternalData/Ap_Forecast
cd ${APHOME}

#Historic averages
wget ftp://ftp.ngdc.noaa.gov/STP/GEOMAGNETIC_DATA/INDICES/KP_AP/$1

mv $1 NGDC_NOAA_Archive/$1


