rm -f atmo.dat
rm -f Clev0.met
rm -f Clev0_raypaths.dat
rm -f Clev0_results.dat
rm -f G2S_SC_*_T_res.raw
rm -f G2S_SC_*_U_res.raw
rm -f G2S_SC_*_V_res.raw
rm -f load_GeoAc_atmo.m
rm -f load_GeoAc_raypaths.m
rm -f load_StationInfo.m
rm -f plot_GeoAc_profile.m
